# Uso básico de los DataFrame de Pandas

Los `DataFrames` son tablas bidimensionales de valores formadas por filas y columnas. Las columnas tienen un nombre y las filas tienen un índice.

## Creación 
Se puede cargar un DataFrame de manera sencilla desde ficheros CSV o Excel.

In [1]:
import pandas as pd

# CSV de datos.gob.es 
# Nº de Médicos por Comunidades, Ciudades autónomas y Provincias de colegiación, edad y sexo
df = pd.read_csv('https://www.ine.es/jaxi/files/tpx/csv_bdsc/59167.csv', sep=';')

# Si la web del INE devuelve error 500, se puede descargar manualmente y abrir desde el disco duro
# df = pd.read_csv('59167.csv', sep=';')

print(df.dtypes)
display(df)

Total Nacional                          str
Comunidades y Ciudades Autónomas        str
Provincias                              str
Edad                                    str
Sexo                                    str
Total                               float64
dtype: object

,Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Edad,Sexo,Total
0,Total Nacional,NaN,NaN,Total,Total,292.413
1,Total Nacional,NaN,NaN,Total,Hombres,136.321
2,Total Nacional,NaN,NaN,Total,Mujeres,156.092
3,Total Nacional,NaN,NaN,Menores de 35 años,Total,61.297
4,Total Nacional,NaN,NaN,Menores de 35 años,Hombres,20.492
...,...,...,...,...,...,...
1507,Total Nacional,19 Melilla,NaN,De 70 y más años,Hombres,20.000
1508,Total Nacional,19 Melilla,NaN,De 70 y más años,Mujeres,5.000
1509,Total Nacional,19 Melilla,NaN,No consta,Total,0.000
1510,Total Nacional,19 Melilla,NaN,No consta,Hombres,0.000
1511,Total Nacional,19 Melilla,NaN,No consta,Mujeres,0.000

También se pueden crear DataFrame a partir de una lista de filas, asignando nombres a las columnas. El caso más sencillo sería el de una tabla de una única columna llamada `'Resultado'`

In [2]:
datos = [5, 3, 5, 1, 4, 6]
df = pd.DataFrame(datos, columns=['Resultado'])
df

   Resultado
0          5
1          3
2          5
3          1
4          4
5          6

Como se ve, aunque no hemos indicado nada, automáticamente se ha incluido un índice numérico incremental en las filas.

Si las filas están formadas por varias columnas, los datos serán una lista de listas:

In [3]:
datos = [['España', 'Madrid', 657],
         ['Canadá', 'Ottawa', 70],
         ['Venezuela', 'Caracas', 1037],
         ['Japón', 'Tokio', 6],
         ['Nueva Zelanda','Wellington', 1],
         ['Botsuana', 'Gaborone', 1014]
        ]
df_capitales = pd.DataFrame(datos,
                            columns=['País', 'Capital', 'Altura capital'])
df_capitales

            País     Capital  Altura capital
0         España      Madrid             657
1         Canadá      Ottawa              70
2      Venezuela     Caracas            1037
3          Japón       Tokio               6
4  Nueva Zelanda  Wellington               1
5       Botsuana    Gaborone            1014

Finalmente, podemos indicar el índice de cada fila, que no siempre debe ser un número (en este caso son cadenas de texto)

In [4]:
datos = [['Madrid', 657],
         ['Ottawa', 70],
         ['Caracas', 1037],
         ['Tokio', 6],
         ['Wellington', 1],
         ['Gaborone', 1014]
        ]
df_capitales2 = pd.DataFrame(datos, 
                            columns=['Capital', 'Altura capital'],
                            index=['España', 'Canadá', 'Venezuela', 'Japón','Nueva Zelanda', 'Botsuana'] )
df_capitales2

                  Capital  Altura capital
España             Madrid             657
Canadá             Ottawa              70
Venezuela         Caracas            1037
Japón               Tokio               6
Nueva Zelanda  Wellington               1
Botsuana         Gaborone            1014

## Acceso a los datos

In [5]:
# Acceso a una columna, que devuelve una Serie
print(type(df_capitales.Capital))
df_capitales.Capital

<class 'pandas.Series'>

0        Madrid
1        Ottawa
2       Caracas
3         Tokio
4    Wellington
5      Gaborone
Name: Capital, dtype: str

In [6]:
# Acceso a una columna, notación alternativa
df_capitales['Altura capital']

0     657
1      70
2    1037
3       6
4       1
5    1014
Name: Altura capital, dtype: int64

In [7]:
# Selección de algunas columnas
df_capitales[['País', 'Altura capital']]

            País  Altura capital
0         España             657
1         Canadá              70
2      Venezuela            1037
3          Japón               6
4  Nueva Zelanda               1
5       Botsuana            1014

In [8]:
# Ver los nombres de las columnas
df_capitales.columns

Index(['País', 'Capital', 'Altura capital'], dtype='str')

In [9]:
# Ver los índices de las filas
df_capitales.index

RangeIndex(start=0, stop=6, step=1)

In [10]:
# Ver los índices de las filas
df_capitales2.index

Index(['España', 'Canadá', 'Venezuela', 'Japón', 'Nueva Zelanda', 'Botsuana'], dtype='str')

In [11]:
# Ver datos en bruto
df_capitales2.values

array([['Madrid', 657],
       ['Ottawa', 70],
       ['Caracas', 1037],
       ['Tokio', 6],
       ['Wellington', 1],
       ['Gaborone', 1014]], dtype=object)

In [12]:
# Acceso a una fila usando su posición
df_capitales.iloc[0]

País              España
Capital           Madrid
Altura capital       657
Name: 0, dtype: object

In [13]:
# Acceso a una fila usando su posición
df_capitales2.iloc[0]

Capital           Madrid
Altura capital       657
Name: España, dtype: object

In [14]:
# Acceso a fila usando su índice
df_capitales.loc[0]

País              España
Capital           Madrid
Altura capital       657
Name: 0, dtype: object

In [15]:
# Acceso a una fila usando su etiqueta
df_capitales2.loc['España']

Capital           Madrid
Altura capital       657
Name: España, dtype: object

## Modificación de DataFrames

In [16]:
# Añadir una columna con valor constante
df_capitales2['Balones Oro'] = 0
df_capitales2

                  Capital  Altura capital  Balones Oro
España             Madrid             657            0
Canadá             Ottawa              70            0
Venezuela         Caracas            1037            0
Japón               Tokio               6            0
Nueva Zelanda  Wellington               1            0
Botsuana         Gaborone            1014            0

In [17]:
# Añadir una columna con distintos valores
df_capitales2['Num. equipos'] = [25, 20, 6, 44, 3, 9]
df_capitales2

                  Capital  Altura capital  Balones Oro  Num. equipos
España             Madrid             657            0            25
Canadá             Ottawa              70            0            20
Venezuela         Caracas            1037            0             6
Japón               Tokio               6            0            44
Nueva Zelanda  Wellington               1            0             3
Botsuana         Gaborone            1014            0             9

In [18]:
# Seleccionar filas
filtro = df_capitales['Altura capital'] > 100
df2 = df_capitales[filtro]
df2

        País   Capital  Altura capital
0     España    Madrid             657
2  Venezuela   Caracas            1037
5   Botsuana  Gaborone            1014

In [19]:
# El filtro creado es una Serie de tantos booleanos como filas. Se seleccionará únicamente aquellas filas asociadas a True
filtro

0     True
1    False
2     True
3    False
4    False
5     True
Name: Altura capital, dtype: bool

In [20]:
# Pero se podría haber construido el filtro "a mano"
df_capitales[[True, False, True, False, False, True]]

        País   Capital  Altura capital
0     España    Madrid             657
2  Venezuela   Caracas            1037
5   Botsuana  Gaborone            1014