# Preprocesamiento y análisis de datos en Pandas

In [1]:
import pandas as pd

# Distribución del gasto turístico y gasto medio diario realizado según continente de destino
gasto = pd.read_csv('https://www.ine.es/jaxiT3/files/t/csv_bdsc/58705.csv', sep=';')
gasto

     Continentes  Gasto Turístico  Periodo          Total
0         Europa  Gasto turístico  2026M03  1.334.382.301
1         Europa  Gasto turístico  2026M02  1.022.714.973
2         Europa  Gasto turístico  2026M01  1.402.721.441
3         Europa  Gasto turístico  2025M12  1.523.722.714
4         Europa  Gasto turístico  2025M11  1.276.187.742
...          ...              ...      ...            ...
1822     Oceanía    Gasto tarjeta  2019M05      2.311.736
1823     Oceanía    Gasto tarjeta  2019M04      2.744.452
1824     Oceanía    Gasto tarjeta  2019M03      3.350.274
1825     Oceanía    Gasto tarjeta  2019M02      3.438.584
1826     Oceanía    Gasto tarjeta  2019M01      4.338.701

[1827 rows x 4 columns]

In [2]:
# Podemos ver en detalle los valores únicos en la columna Total
gasto.Total.unique()

<ArrowStringArray>
['1.334.382.301', '1.022.714.973', '1.402.721.441', '1.523.722.714',
 '1.276.187.742', '1.229.732.522', '1.829.790.810', '3.326.894.617',
 '2.027.691.289', '1.460.273.991',
 ...
     '3.413.067',     '2.632.248',     '3.880.836',     '2.528.075',
     '1.706.860',     '2.311.736',     '2.744.452',     '3.350.274',
     '3.438.584',     '4.338.701']
Length: 1639, dtype: str

In [3]:
# Gasto total en todas las filas
print('Suma de totales:', gasto.Total.sum(), '\n')  # Sin ningún sentido
print('Total máximo:', gasto.Total.max(), '\n')
print('Total mínimo:', gasto.Total.min(), '\n')
gasto.Total.describe()

Suma de totales: 1.334.382.3011.022.714.9731.402.721.4411.523.722.7141.276.187.7421.229.732.5221.829.790.8103.326.894.6172.027.691.2891.460.273.9911.311.471.1211.469.464.9411.326.359.1901.033.092.4181.239.427.0321.371.647.8561.074.702.4361.217.862.8791.947.519.3643.002.862.1921.951.928.6681.431.300.2871.091.911.9811.267.765.2591.202.819.5901.068.073.9971.187.547.9221.521.982.858930.793.9301.227.154.6521.639.071.3992.873.445.9631.609.063.9311.135.745.3701.033.532.8751.183.550.393772.913.296786.190.2651.108.130.5761.126.667.217817.130.343938.004.4721.232.193.3442.313.991.1821.541.669.002844.601.147584.302.1811.095.575.630651.476.699360.075.672460.251.955639.066.475573.564.832446.504.851729.228.0351.024.512.803484.332.082230.851.500101.081.661...111.237.774..122.209.350227.361.300442.571.891192.921.129...252.325.883568.347.105780.167.583742.191.540577.974.111781.270.2341.161.367.2282.388.190.7301.398.671.037954.125.344767.211.5991.053.193.664753.931.330499.170.429716.154.647161,28159,15106,71143,91178,59162,62118,5593,67124,86153,09149,55136,05122,53119,52114,43128,48142,53158,192,0585,99118,45153,47153,36144,28138,69124,05105,4123,32129,36155,44102,793,38117,44150,77137,58115,37133,66135,9987,03134,5136,02125,54100,4877,55105,36117,86121,56100,16103,27118,4871,46111,87110,5290,3167,5558,2371,2879,4191,37...37,2..73,0959,5160,7576,77...104,55106,2374,38102119,35114,4196,6382,7891,84128,87130,82112,3117,2293,7977,24462.022.681391.933.563469.438.565594.240.599444.550.134489.850.111590.490.545959.909.817686.954.725504.465.297465.543.647505.511.469442.324.220376.804.782468.363.969590.740.080449.113.477482.633.479566.653.995932.448.123665.874.085489.048.917444.559.528445.101.611448.083.088374.014.120427.268.517551.763.721396.262.668470.336.796548.849.644880.252.091621.130.870447.804.139412.857.612460.515.200380.932.386330.254.521402.130.236497.470.150380.010.376417.063.695490.072.253810.621.279557.680.686399.421.286351.588.698390.031.352312.739.325241.475.485258.816.142350.133.130301.311.413347.106.293368.640.575498.293.558306.681.801201.348.768153.821.507...106.101.374..190.911.473222.552.289333.421.649215.494.999...170.164.803283.712.900332.723.190403.022.866311.034.123346.333.811415.475.596696.899.405485.202.637344.462.423319.337.178361.926.642305.194.522257.998.218312.243.31852.503.98344.236.71971.861.91946.154.94651.357.88645.176.78071.514.66598.263.09658.016.57237.614.41845.666.18455.295.96340.837.05037.587.89549.668.62037.794.24136.453.21440.385.51364.179.90386.919.67951.111.04335.196.88030.222.44735.960.43537.830.68233.908.63437.615.97636.211.70726.072.87432.781.53639.435.38167.143.78934.223.14623.193.17622.630.93830.313.08120.888.55718.072.18533.541.41837.561.07831.773.74035.060.56544.383.16972.877.37248.288.66824.258.02718.418.17833.277.41018.950.5087.367.0408.629.86813.460.88517.275.85511.080.42214.763.37717.589.72810.298.5214.856.1012.669.828...5.453.033..2.414.5563.319.2083.525.0852.874.503...15.047.77530.012.66141.701.68033.656.95629.473.25741.860.41745.124.05579.959.48238.108.52628.367.97328.051.85443.464.54730.919.36321.483.12532.214.164191,88193,75139,49131,12158,65139,74132,0295,54136,86143,13150,02148,61119,97113,12135,76134,25141,32162,4104,95103,03141,57151,77151,37142,59156,37131,74112,11133,98121,54139,7882,7794,46107,06124,9898,7193,54106,1392,674,4688,5478,9977,762,6960,0872,587,1786,5762,9164,5868,4555,1491,2273,7561,6440,3340,3748,4640,947,37...36,91..29,2722,0228,3445,13...78,7782,1656,5291,1781,5188,8657,1857,7367,1674,0881,5475,9575,4863,0150,1918.085.23816.608.38622.752.19520.070.11019.199.40319.676.00323.073.94633.337.99820.944.43616.897.26218.970.66621.903.71916.703.11216.057.93321.615.06819.503.06318.233.22218.744.54121.056.57330.413.05920.422.13216.442.59617.159.29217.347.12517.514.78215.239.46217.653.10317.591.63415.760.06417.576.13120.293.57528.046.24720.363.50416.237.01916.454.68418.506.57617.012.39314.359.83319.268.75419.535.28517.326.95918.368.92820.641.45228.936.54720.568.15214.564.95813.842.01114.733.13512.357.3378.533.9608.897.61811.130.69512.964.19312.595.46411.309.20612.853.02310.588.6418.368.8858.199.323...9.092.793..8.526.4127.542.0427.642.4528.516.328...13.195.88915.986.25418.818.01618.703.82117.800.48317.988.21819.068.39925.103.77816.930.18313.608.87013.952.00516.391.34914.002.95511.985.81514.623.044102.883.96070.413.057108.507.23488.489.28399.035.67282.295.929164.252.616216.754.468144.788.22685.946.025104.279.258125.414.746118.845.66683.546.300109.436.008115.844.860121.690.427123.538.627154.330.695227.996.924122.008.22785.912.88193.119.343114.785.011104.369.47688.863.53195.090.337121.693.206101.323.372115.393.918135.636.434220.697.38098.352.66374.955.26581.503.112102.370.10364.569.34050.878.01085.597.999101.610.295101.843.049112.051.968142.957.848239.160.122138.704.04582.199.03270.734.580138.459.02571.566.97332.996.44054.998.37582.455.10160.700.07124.914.25235.511.31847.137.16224.482.49013.868.5238.339.334...9.833.242..3.878.3714.592.0415.756.3563.380.924...38.673.84185.714.825118.262.44492.709.31593.297.332121.212.301172.428.822330.194.365152.017.399108.562.771119.217.371153.949.99795.840.17453.230.94588.821.091243,84216,88141,33159,44228,83204,25183,49114,03180,36188,83216,14201,44189,14172,72169,49192,52241,03252,07107,57111,65145,38178,87201,79202,33191,07165,58124,31163,19186,36216,11124,05124,41137,89181,89160,65154,16170,4146,48100,57166,3204,11191,62130,96110,72141,07164,53175,82164,53165,99168,1687,61181,74223,4192,2111,0298,3130,39146,71192,72...80,48..151,17123,5391,09109,19...140,93214,01134,01157,54195,96187,98151,79143,55137,1193,33217,11189,74173,44124,13114,2341.146.64033.187.49941.981.72946.999.34445.689.82644.123.66950.199.65876.291.49848.920.96739.899.87044.487.68449.556.32044.015.19135.884.48245.870.44651.298.72549.564.94849.154.04254.713.16381.566.37052.420.41841.455.13147.797.84749.766.69649.385.29839.477.10445.287.12754.254.13151.194.08553.831.49057.411.25279.814.07350.809.16742.214.94344.720.79051.692.29943.804.09934.093.17043.292.11352.402.13852.902.07855.655.29162.892.48990.541.13557.720.66345.998.61348.311.36254.735.49840.703.88329.554.62736.718.25445.724.09833.151.51722.177.43920.979.25526.037.77918.476.70214.779.04014.682.123...11.189.234..9.135.6118.098.9548.198.2796.908.314...27.863.63942.214.66649.705.35359.970.42055.634.26859.872.78268.589.069104.411.09464.215.23450.095.21755.736.45060.081.87148.168.30739.247.21748.458.37026.359.50320.931.30635.998.84320.068.03416.399.13511.604.00433.699.04256.784.97036.542.48423.851.14726.967.63432.440.06525.945.70224.001.63033.121.98927.774.04022.449.28818.284.76025.819.41643.829.99324.418.87218.159.48515.577.49221.403.04523.546.22023.633.94128.672.80031.504.68420.905.95720.801.21225.443.99147.521.61224.848.48315.088.56615.364.35021.900.08318.737.48120.114.94030.394.66123.972.47717.812.82116.041.21223.321.34947.746.73829.820.61512.021.31311.110.54022.632.40916.687.1859.675.51818.360.01618.864.38612.603.9177.216.37313.434.65023.883.81410.445.0534.656.9712.855.160...5.398.229..1.239.4661.425.2221.423.5861.124.969...12.438.86717.466.49825.604.57021.090.59018.091.75817.747.84526.126.82957.102.54429.947.17518.559.29019.142.19824.817.09522.692.56218.713.69626.671.378205,78182,97122,98131,93151,97122,5163,25125,11175,5206,1217,53204,86146,73151,61144,55190,81206,55198,0598,12107,42138,68192,05193,28198,53193,82170,69138,58198,3195,87227,47124,09127,09160,07186,08176,27170,25215,52211,64123,44181,14148,35142,21103,1884,71113,97128,7159,63127,04155,46165,7990,22180,75138,73109,9277,8779,293,2698,24136,07...73,2..128,6198,29117,14268,74...172,56142,1790,41156,83145,61131,59115,01107,29120,07135,32155,19142,86149,36132,8699,4312.331.73011.059.20015.227.00013.663.72810.493.6559.199.34610.385.90218.023.43012.433.9408.981.8459.765.22811.101.30211.429.61411.209.47414.958.19114.717.56811.688.47910.041.92911.503.43518.244.68512.474.3979.274.3529.359.57410.479.85112.437.01611.701.63013.554.87613.834.68410.729.69510.184.67611.851.83517.915.81212.869.3869.363.8379.502.85211.772.14112.447.30411.654.25614.025.37414.333.67211.911.64910.998.37013.024.30920.456.42114.570.6609.702.26510.471.77511.812.06411.541.59010.079.42812.904.05812.760.2629.313.5098.484.7549.571.47314.217.1569.308.4786.818.9076.850.919...7.070.253..4.164.3043.687.2553.799.1544.166.780...8.983.46011.469.67413.588.77013.571.66811.393.49010.507.56811.997.19419.120.30113.152.7789.671.56910.372.50411.184.19611.157.30310.785.20112.794.69492.765.97182.780.479138.612.86779.053.14164.907.41039.255.90092.107.513121.345.83783.949.71355.333.45963.910.69477.972.65085.148.56778.620.417110.060.54186.669.67364.871.92750.114.19369.528.76993.217.16057.103.10543.034.02241.925.14661.109.77069.798.20172.197.94692.879.77291.526.21753.097.07446.620.04042.258.78568.370.96036.365.44025.274.29326.791.28337.349.80336.028.52937.428.04763.854.47661.665.77045.936.19042.420.05444.369.85263.822.76147.379.40529.300.89927.195.33952.544.88941.371.81426.810.68042.540.02439.318.45528.464.47215.150.77623.305.10127.955.32215.810.4789.025.9935.403.892...17.208.263..3.071.3704.333.8944.520.6334.458.432...28.028.11146.488.29972.473.43759.817.73151.239.15650.356.92458.743.697101.498.95956.861.83141.408.72046.461.55464.088.22571.352.58056.222.73484.723.998195,69183,41122,41135,23162,81121,34147,78100,21164,64173,47176,32160,03128,08135,09116,89162,11178,63173,2496,4794,87138,07173,8182,95176,17177,78151,69113,07167,23168,04188,6490,1596,05116,49136,49119,94109,83138,99129,9382,89203,06169,83177,29117,43112,09147,63173,57226,03146,5181,48209,5693,89200,28156,38140,76108,89103,35149,04181,26255,88...110,44..213,38157,57286,67532,79...184,3718098,31211,35191,56188,48166,99150,77203,49215,06248,08224,68263,18225,48173,8334.887.83933.780.26447.996.72243.447.79833.129.38127.318.92726.988.69838.177.43726.873.44321.905.86024.186.24527.749.45832.002.25230.893.96242.583.00040.611.65930.486.33325.156.64824.645.93734.216.55224.295.65520.294.48022.020.92725.777.76130.922.84929.513.70937.478.19436.292.41825.406.73722.053.47423.013.56629.882.66323.025.18818.973.17319.560.88623.168.55325.805.58823.727.69730.784.03529.843.01123.887.04022.023.89621.352.33326.539.28721.144.80817.634.91519.451.44021.716.49521.940.25619.424.55024.308.09423.488.72917.260.63714.573.91814.633.09016.586.30512.838.06310.503.15510.412.724...15.480.983..8.782.8407.524.8808.087.9438.502.119...20.413.94827.439.16534.413.82834.684.71828.851.46126.375.57626.659.48236.194.43526.510.94121.433.01223.845.73426.494.32829.473.08627.575.80134.800.35670.343.31572.040.627107.557.57385.791.572121.789.57188.013.514109.653.626172.978.70689.269.97557.958.40681.710.315111.587.891110.831.76396.478.072103.363.62180.246.219103.788.58886.472.335106.111.700143.136.87375.826.63755.270.73459.422.73081.848.19781.964.20872.875.71676.391.99678.020.59680.098.28577.517.93788.909.956130.557.94662.026.55248.663.49456.933.74670.247.66853.216.15953.033.73966.669.52975.154.41970.157.88356.370.68454.821.49379.207.09045.431.43129.727.57623.672.23249.089.56734.276.20117.809.14722.737.44625.480.71921.838.36610.984.62412.595.62415.690.8178.006.1236.249.1523.433.548...7.512.199..2.195.2432.866.5192.949.5431.636.537...21.414.71449.015.50079.243.04969.612.79592.887.409103.159.574119.823.442226.592.381113.512.63777.167.19784.684.271128.482.68999.785.91465.242.53891.383.740207,4214,99154,27175,92219,49181,61144,7112,76142,6156,58178,67196,22192,21194,31186,67219,05243,81240,13118,94112,14155,44208,59231,78244,78233,53211,36182,82213,17228,54241,73142,24132,24167,67225,28224,72209,64243,74250,7161,79304,66274,16246,11164,67132,36190,31254,85290,95237,11270,5320,24184,88304,53235,7187,46136,74100,44148,2209,69259,71...134,15..140,64113,56183,35190,17...187,34210,11153,25243,86250,78256,59202,47166,35208,5272,32309,7284,91305,86256,52187,1828.407.10131.715.20940.896.54838.372.03745.015.97839.131.77936.836.07953.806.35533.790.06425.800.57633.103.73741.813.16035.446.74732.668.82637.868.74938.045.02443.777.48337.164.82135.446.88849.915.71731.178.55824.297.08628.468.00932.699.29835.173.03330.064.79232.439.06132.426.61636.015.95333.336.85133.732.93044.664.55428.442.10323.380.07326.484.66031.138.50329.725.35525.622.82827.839.92333.114.38531.440.30525.260.05522.991.93329.578.62018.359.16415.644.91515.442.84518.507.58916.947.72812.686.82513.405.82615.893.19913.327.95310.762.7948.766.67010.174.6807.518.8047.705.8707.505.784...8.251.575..5.124.0994.884.8454.715.0954.654.917...15.330.11024.825.30133.542.69735.488.44239.970.45238.960.59239.348.43763.611.21838.385.32426.763.86630.852.60038.404.89633.531.72426.950.72933.457.1537.482.7977.262.69010.318.0996.233.5177.451.0845.184.6857.951.51810.769.2025.892.2373.314.0065.338.2975.377.2168.866.6538.395.69610.228.4126.276.0636.352.2164.772.1877.142.1068.347.9315.037.5203.627.7683.851.3895.777.4997.958.1328.101.9359.620.9208.580.7137.143.6345.975.1006.544.9069.717.7665.347.7103.040.6593.689.8485.587.9136.065.5365.276.9049.331.8905.938.2685.460.8034.787.8113.976.8434.694.6183.231.3621.493.7891.487.0272.852.8251.547.125501.394610.819430.378193.543...211.016186.575136.821...352.234..98.978.200.931217.269...3.778.7065.922.5809.740.5756.231.9776.336.5855.941.5634.335.0149.191.1514.384.1811.712.3353.508.4775.480.5446.984.2266.466.5139.389.297230,83231,71146,94162,76210,7177,18191143,13177,97175,82217,33162,5183,38192,37173,65150,04180,02178,36137,45126,2178,51209,07220,54213,36213,52191,07157,25187,77204,28216,6163,03143,89189,89195,69177,34158,45196,85199,46143,13480,74372,9351,08248,28235,62289,33314,34358,36344,88348,37216,25181,69254,65321,6...477,15762,79863,96...527,66..387,44.717,93483,53...286,86344187,35306,69384,34417,59258,9242,43279,95221,31387,14350,14430,7401,45307,152.550.1702.654.5693.361.5332.943.5082.928.0912.559.9462.165.2722.851.2601.793.2851.308.9621.880.4391.947.9782.539.7252.502.5763.281.3283.089.0412.892.5682.418.5832.000.6202.616.2121.721.5031.321.7031.556.3831.944.9782.709.0202.545.3963.122.6773.061.6112.909.9392.358.4871.904.4362.615.9391.805.3591.295.4431.536.1092.190.3572.883.0752.156.3602.783.9012.710.1722.529.0512.231.5491.778.2291.975.5481.458.2531.037.2941.126.0411.235.101960.826593.068604.791487.516347.530...375.360394.352448.160...554.874..420.891.443.106613.373...2.631.2473.105.0324.150.5984.188.9303.872.6403.413.0672.632.2483.880.8362.528.0751.706.8602.311.7362.744.4523.350.2743.438.5844.338.701

Total máximo: 99.785.914

Total mínimo: .

count     1827
unique    1639
top          .
freq       180
Name: Total, dtype: object

In [4]:
# Problema 1: los totales son cadenas de texto con el punto (".") como separador de millares => eliminarlo
gasto['total_limpio'] = gasto.Total.apply(lambda x: x.replace('.', ''))
gasto

     Continentes  Gasto Turístico  Periodo          Total total_limpio
0         Europa  Gasto turístico  2026M03  1.334.382.301   1334382301
1         Europa  Gasto turístico  2026M02  1.022.714.973   1022714973
2         Europa  Gasto turístico  2026M01  1.402.721.441   1402721441
3         Europa  Gasto turístico  2025M12  1.523.722.714   1523722714
4         Europa  Gasto turístico  2025M11  1.276.187.742   1276187742
...          ...              ...      ...            ...          ...
1822     Oceanía    Gasto tarjeta  2019M05      2.311.736      2311736
1823     Oceanía    Gasto tarjeta  2019M04      2.744.452      2744452
1824     Oceanía    Gasto tarjeta  2019M03      3.350.274      3350274
1825     Oceanía    Gasto tarjeta  2019M02      3.438.584      3438584
1826     Oceanía    Gasto tarjeta  2019M01      4.338.701      4338701

[1827 rows x 5 columns]

In [5]:
# Problema 2: 'total_limpio' tiene algunos valores vacíos '' => eliminar esas filas
gasto[gasto['total_limpio'] == '']
# Hay varias filas con el total_limpio vacío

     Continentes  Gasto Turístico  Periodo Total total_limpio
59        Europa  Gasto turístico  2021M04     .
60        Europa  Gasto turístico  2021M03     .
61        Europa  Gasto turístico  2021M02     .
63        Europa  Gasto turístico  2020M12     .
64        Europa  Gasto turístico  2020M11     .
...          ...              ...      ...   ...          ...
1804     Oceanía    Gasto tarjeta  2020M11     .
1806     Oceanía    Gasto tarjeta  2020M09     .
1809     Oceanía    Gasto tarjeta  2020M06     .
1810     Oceanía    Gasto tarjeta  2020M05     .
1811     Oceanía    Gasto tarjeta  2020M04     .

[180 rows x 5 columns]

In [6]:
gasto = gasto[gasto['total_limpio'] != '']
gasto
# Nos quedamos con las filas que tienen total_limpio no vacío

     Continentes  Gasto Turístico  Periodo          Total total_limpio
0         Europa  Gasto turístico  2026M03  1.334.382.301   1334382301
1         Europa  Gasto turístico  2026M02  1.022.714.973   1022714973
2         Europa  Gasto turístico  2026M01  1.402.721.441   1402721441
3         Europa  Gasto turístico  2025M12  1.523.722.714   1523722714
4         Europa  Gasto turístico  2025M11  1.276.187.742   1276187742
...          ...              ...      ...            ...          ...
1822     Oceanía    Gasto tarjeta  2019M05      2.311.736      2311736
1823     Oceanía    Gasto tarjeta  2019M04      2.744.452      2744452
1824     Oceanía    Gasto tarjeta  2019M03      3.350.274      3350274
1825     Oceanía    Gasto tarjeta  2019M02      3.438.584      3438584
1826     Oceanía    Gasto tarjeta  2019M01      4.338.701      4338701

[1647 rows x 5 columns]

In [7]:
# Problema 3: Algunas filas tienen valores decimales separados con coma
# (',') en 'total_limpio', que es algo muy español pero funciona mal 
# en Python => cambiar comas por puntos
gasto[gasto['total_limpio'].str.find(',') >= 0]

     Continentes        Gasto Turístico  Periodo   Total total_limpio
87        Europa  Gasto medio turístico  2026M03  161,28       161,28
88        Europa  Gasto medio turístico  2026M02  159,15       159,15
89        Europa  Gasto medio turístico  2026M01  106,71       106,71
90        Europa  Gasto medio turístico  2025M12  143,91       143,91
91        Europa  Gasto medio turístico  2025M11  178,59       178,59
...          ...                    ...      ...     ...          ...
1735     Oceanía  Gasto medio turístico  2019M05  387,14       387,14
1736     Oceanía  Gasto medio turístico  2019M04  350,14       350,14
1737     Oceanía  Gasto medio turístico  2019M03   430,7        430,7
1738     Oceanía  Gasto medio turístico  2019M02  401,45       401,45
1739     Oceanía  Gasto medio turístico  2019M01  307,15       307,15

[545 rows x 5 columns]

In [8]:
gasto['total_limpio'] = gasto.total_limpio.apply(lambda x: x.replace(',', '.'))
gasto

     Continentes  Gasto Turístico  Periodo          Total total_limpio
0         Europa  Gasto turístico  2026M03  1.334.382.301   1334382301
1         Europa  Gasto turístico  2026M02  1.022.714.973   1022714973
2         Europa  Gasto turístico  2026M01  1.402.721.441   1402721441
3         Europa  Gasto turístico  2025M12  1.523.722.714   1523722714
4         Europa  Gasto turístico  2025M11  1.276.187.742   1276187742
...          ...              ...      ...            ...          ...
1822     Oceanía    Gasto tarjeta  2019M05      2.311.736      2311736
1823     Oceanía    Gasto tarjeta  2019M04      2.744.452      2744452
1824     Oceanía    Gasto tarjeta  2019M03      3.350.274      3350274
1825     Oceanía    Gasto tarjeta  2019M02      3.438.584      3438584
1826     Oceanía    Gasto tarjeta  2019M01      4.338.701      4338701

[1647 rows x 5 columns]

In [9]:
# Problema 4: 'total_limpio' es una columna de cadenas de texto, pasar a número
gasto['total_limpio'] = gasto['total_limpio'].apply(lambda x: float(x))
gasto

     Continentes  Gasto Turístico  Periodo          Total  total_limpio
0         Europa  Gasto turístico  2026M03  1.334.382.301  1.334382e+09
1         Europa  Gasto turístico  2026M02  1.022.714.973  1.022715e+09
2         Europa  Gasto turístico  2026M01  1.402.721.441  1.402721e+09
3         Europa  Gasto turístico  2025M12  1.523.722.714  1.523723e+09
4         Europa  Gasto turístico  2025M11  1.276.187.742  1.276188e+09
...          ...              ...      ...            ...           ...
1822     Oceanía    Gasto tarjeta  2019M05      2.311.736  2.311736e+06
1823     Oceanía    Gasto tarjeta  2019M04      2.744.452  2.744452e+06
1824     Oceanía    Gasto tarjeta  2019M03      3.350.274  3.350274e+06
1825     Oceanía    Gasto tarjeta  2019M02      3.438.584  3.438584e+06
1826     Oceanía    Gasto tarjeta  2019M01      4.338.701  4.338701e+06

[1647 rows x 5 columns]

In [10]:
# Gasto total en todas las filas
print('Suma de totales:', gasto.total_limpio.sum(), '\n')
print('Total máximo:', gasto.total_limpio.max(), '\n')
print('Total mínimo:', gasto.total_limpio.min(), '\n')
gasto.total_limpio.describe()

Suma de totales: 153914710893.46002

Total máximo: 3326894617.0

Total mínimo: 22.02

count    1.647000e+03
mean     9.345155e+07
std      2.831788e+08
min      2.202000e+01
25%      1.937850e+02
50%      1.177214e+07
75%      4.418019e+07
max      3.326895e+09
Name: total_limpio, dtype: float64

In [11]:
# Principales valores de estadística descriptiva
# sobre columna de cadenas de texto
gasto.Continentes.describe()

count       1647
unique         7
top       Europa
freq         237
Name: Continentes, dtype: object

In [12]:
# Gasto mediano
gasto.total_limpio.median()

np.float64(11772141.0)